### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by sckott** [iobis/api-docs#5]
Seems to be down for me, noticed as the `pyobis` tests are failing with 500 server errors

**Comment by sckott** [comment]
@pieterprovoost

**Comment by pieterprovoost** [comment]
Yes, and it could take a few days te be up again, apologies for that. The API still runs on the staging environment (which is rebuilt every few months), but we'll move to production soon.

**Comment by sckott** [comment]
Thanks for the update

**Comment by pieterprovoost** [comment]
Back up.
